dist: trusty
language: elixir
elixir:
  - 1.5.1
otp_release:
  - 20.0
sudo: required
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - MIX_ENV=test mix deps.compile
script:
  - mix test
notifications:
  recipients:
    - ekuklu@icloud.com
    - akdilsiz@tecpor.com
